uyuni-project/retail

dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/saltboot-root.sh
dracut-saltboot/saltboot/saltboot.sh

Dracut saltboot is a copy of kiwi-desc-saltboot script and on some places still relied on variables and functions provided by old kiwi hooks. They are no longer available in dracut.
This covers:
* source wicked network information to access IPADDR and DNSDOMAIN variables
* replase `systemException` functions by log and reboot actions
During development was discovered issue when terminal harddrive was replaced and then boot failed. This PR then also adds timeout script which stops dracut waiting for missing partition and continue as a new deployment.

Adapt dracut-saltboot to dracut environment

---

branch-network-formula/branch-network-formula.changes
branch-network-formula/metadata/form.yml
dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/saltboot.sh
kiwi-desc-saltboot/kiwi-desc-saltboot.changes
kiwi-desc-saltboot/saltboot/suse-SLES12/root/saltboot.sh
python-susemanager-retail/python-susemanager-retail.changes
python-susemanager-retail/susemanager/retail/branch.py

- introduce USE_FQDN_MINION_ID kernel command line option to control
if plain hostname (if not set) or full FQDN (if set) should be used
for minion id. This is in effect only if terminal IP is reverse
resolvable
- introduce DISABLE_ID_PREFIX kernel command line option to control
if BRANCH_ID should be prefixed (if not set) to the minion id or
not (if set)

Add FQDN as an option as minion id

---

branch-network-formula/branch-network-formula.changes
branch-network-formula/branch-network/files/susemanager-retail.conf.template
branch-network-formula/branch-network/init.sls

Add apache2 configuration to allow http access to saltboot directory. This is intended to replace ftp in the future.
apache2 is supposed to be already installed as part of proxy.

Allow http access to saltboot directory

---

branch-network-formula/branch-network-formula.changes
branch-network-formula/branch-network/files/susemanager-retail.conf.template

This seems to be required by qemu-ovmf uefi bios.

Handle application/efi mime type

---

saltboot-formula/_states/saltboot.py
saltboot-formula/saltboot-formula.changes

cp.get_file_str is not optimal for reading local files, it tries to communicate with salt master etc.

Use file.read instead of cp.get_file_str

---

dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/module-setup.sh

By default, dracut --hostonly installs raid modules only if root is on raid device. Saltboot needs it for any raid device configured in pillars.

Force installation of raid1 kernel module

---

saltboot-formula/_states/saltboot.py

Saltboot recognizes following pillars:
- saltboot_download_server: specifies from where download the images, kernel, etc.
- saltboot_download_protocol: specifies what protocol to use for download

Allow pillar customizable download urls

---

dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/module-setup.sh
dracut-saltboot/saltboot/saltboot.sh

This enables similar behavior as in kiwi-desc-saltboot - existing RAIDS are assembled so saltboot can mount them and check for existing configuration.

Assemble existing RAIDs before searching for salt configuration

---

POS_Image-Graphical7/POS_Image-Graphical7.changes
POS_Image-Graphical7/graphical-7.0.0/config.sh
POS_Image-Graphical7/graphical-7.0.0/root/etc/sysconfig/bootloader
POS_Image-JeOS7/POS_Image-JeOS7.changes
POS_Image-JeOS7/jeos-7.0.0/config.sh
POS_Image-JeOS7/jeos-7.0.0/root/etc/sysconfig/bootloader

With Secure Boot disabled, the image can't boot from hdd on Secure Boot enabled machines.
With Secure Boot enabled, it can boot anywhere.

Enable Secure Boot by default

---

saltboot-formula/metadata/form.yml
saltboot-formula/metadata/metadata.yml
saltboot-formula/saltboot-formula.changes

Update saltboot form and metadata to use new formula features
Also limit RAID level to only 1 which is actually tested and works with local boot. Can be changed if there is demand.

Update saltboot form and metadata to use new formula features

---

saltboot-formula/_states/saltboot.py
saltboot-formula/saltboot-formula.changes

kexec with default options does not work with UEFI Secure Boot. This is typically not fatal, the terminal just reboots as a fallback.
The only situation where it causes real problems is boot from USB when there is a different kernel version on Branch Server.
kexec with --kexec-syscall-auto  should work everywhere.
The option is not available on older distros.

use kexec --kexec-syscall-auto if possible

---

dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/saltboot.sh

Use automatic udev based RAID assembly only in the first phase, to get previous salt configuration.
In second phase all changes to RAID devices are controlled by saltboot state.

Disable automatic RAID assembly in saltboot phase

---

image-sync-formula/image-sync-formula.changes
image-sync-formula/image-synchronize/sync.sls

Image sync state requires branch-network pillars to get the directory where to sync images. Use default `/srv/saltboot` if that pillar is missing so image-sync can be applied on non branch minions as well.

Allow image-sync state on regular minion

---

POS_Image-Graphical7/POS_Image-Graphical7.changes
POS_Image-Graphical7/graphical-7.0.0/config.xml
POS_Image-JeOS7/POS_Image-JeOS7.changes
POS_Image-JeOS7/jeos-7.0.0/config.xml

- plymouth-plugin-label-ft is now mandatory to all *7 templates and templates to be of SLE15SP2 version
- add optional dracut-wireless comment section and move wpa_suplicant there

Add plymouth-plugin-label-ft package

---

dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/module-setup.sh
dracut-saltboot/saltboot/saltboot.sh

Fix for https://github.com/SUSE/spacewalk/issues/12005
Allow configuring autosign grains in image sources or on kernel commandline.

Support autosign grains in saltboot intrd

---

saltboot-formula/_states/saltboot.py
saltboot-formula/metadata/form.yml
saltboot-formula/saltboot-formula.changes
saltboot-formula/saltboot-reactor/pxe_update.sls
saltboot-formula/saltboot/init.sls

https://github.com/SUSE/spacewalk/issues/12282
Kernel parameters specified in Saltboot formula are appended to kernel commandline for PXE, kexec and grub.
Kernel parameters specified in PXE formula are used only for PXE boot.

Allow setting terminal kernel parameters in saltboot formula

---

image-sync-formula/_modules/image_sync_usb.py
image-sync-formula/image-sync-formula.changes
image-sync-formula/image-synchronize/sync.sls
image-sync-formula/metadata/images.pillar.example
python-susemanager-retail/python-susemanager-retail.changes
python-susemanager-retail/susemanager/retail/branch.py

Fixes https://github.com/SUSE/spacewalk/issues/12162

Do not use .gz suffix for default initrd symlink

---

POS_Image-Graphical7/POS_Image-Graphical7.changes
POS_Image-Graphical7/graphical-7.0.0/config.sh
POS_Image-JeOS7/POS_Image-JeOS7.changes
POS_Image-JeOS7/jeos-7.0.0/config.sh

linuxefi grub command does not work on arm, this change is copied from Kiwi OEM image configuration.

Use linuxefi only on x86

---

branch-network-formula/branch-network-formula.changes
branch-network-formula/branch-network/files/defaults.template
branch-network-formula/branch-network/init.sls
dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/saltboot.sh

saltboot/defaults is used as a fallback if certain values are missing on kernel commandline

Create and use saltboot/defaults file

---

POS_Image-RPi-Bootstrap/rpm-properties.xml

SUMA builds images for both aarch and x86_64, but we want only the
aarch one.

Add exclude arch to the RPi image props

---

dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/module-setup.sh

This implements dependency solving for nonexecutable python library files which are ignored by dracut-install.

Fix dependencies of python libs (bsc#1188846)

---

saltboot-formula/_states/saltboot-sle11.py
saltboot-formula/_states/saltboot.py
saltboot-formula/saltboot-formula.changes

- Some configurations without initial filesystem (filesystem set to None) could trigger string operations on None.
Prevent this by returning empty string.
- commit 33a6428 added extra boot_images option to `bootloader_updated`, but this was not added to SLE11 variant of saltboot.
This is then reported as warning and failed state when deploying
SLE11 image
fixes https://github.com/SUSE/spacewalk/issues/16342

Prevent string operations on None

---

saltboot-formula/_states/saltboot-sle11.py
saltboot-formula/_states/saltboot.py
saltboot-formula/saltboot-formula.changes

Make sure that `saltboot` part of  image url is modified only if change of the protocol is forced.
Support also removing `saltboot` on protocol change from `http` to `ftp`.

Improve image url modifications

---

saltboot-formula/_states/saltboot.py
saltboot-formula/saltboot-formula.changes

On SLE15 SP4 the default lsblk output replaced "mountpoint" field with "mountpoints".
This PR specifies, which fields are required, as suggested in lsblk man page.

Specify required columns in lsblk output

---

image-sync-formula/_states/image_sync.py
image-sync-formula/image-sync-formula.changes

Salt tries to show changes if a file differs. For large images it can lead to OOM.
This PR disables it.
This code path is not used for bundle images, that's why we did not hit it earlier.

Do not try to show changes in images (bsc#1199998)

---

dracut-saltboot/dracut-saltboot.spec

Because of Uyuni/SUMA client tools check validates that all packages in tools repo are installable just by using base system modules we can't require kiwi-tools which is in development module.
Kiwi-tools are still required in image templates.

Change kiwi-tools requires to recommends

---

POS_Image-Graphical6/graphical-6.0.0/images.sh
POS_Image-Graphical7/graphical-7.0.0/images.sh
POS_Image-JeOS6/jeos-6.0.0/images.sh
POS_Image-JeOS7/jeos-7.0.0/images.sh

SUMA always puts the activation key in /etc/salt.
It is better to move it in images.sh - this is compatible with all SUMA versions.

Move the activation key injected by SUMA

---

saltboot-formula/_states/saltboot.py
saltboot-formula/saltboot-formula.changes

This falls back to installed image if the new image, configured in pillar, can't be downloaded. This happens when the image is not synced yet.
It still ends with a failure if the requested image is missing from pillars and on other misconfigurations.
Fixes: https://github.com/SUSE/spacewalk/issues/18637

Fallback to local boot if the configured image is not synced

---

image-sync-formula/_modules/image_sync.py
image-sync-formula/image-sync-formula.changes
image-sync-formula/image-synchronize/sync.sls

Backport of https://github.com/uyuni-project/retail/pull/104 but disable version sorting by default for 4.2

Backport image sync boot version sorting

---

image-sync-formula/image-sync-formula.changes
image-sync-formula/metadata/form.yml
saltboot-formula/metadata/form.yml
saltboot-formula/metadata/saltboot-group-form.yml
saltboot-formula/saltboot-formula.changes

Expose known pillar values to the form:
- image-sync: use latest boot image as default
- saltboot: ability to select reboot or kexec

Retail form updates

---

branch-network-formula/sysconfig/_states/sysconfig.py

This unnecessary import is causing problems with Salt 3006.0, as `salt.ext.six` has been removed.
Apparently, this import is actually never used, so it seems it is safe to remove it.

Remove unnecessary import of "salt.ext.six"

---

kiwi-desc-saltboot/kiwi-desc-saltboot.changes
kiwi-desc-saltboot/saltboot/suse-SLES12/config.xml

- when KiwiNG is used to build SLE12 images, bootstrap package specified on command line is not propagated to the bootimage. Lets add it explicitely in the image then.

Add osimage cert package to bootstrap for SLE12 images

---

saltboot-formula/_states/saltboot.py
saltboot-formula/saltboot-formula.changes

When dict key is not present, it is not present as `None`, but empty string. Let's ask explicitly for `False` instead and check for that.

Fix custom_info boolean check

---

image-sync-formula/_modules/image_sync.py
image-sync-formula/_states/image_sync.py
image-sync-formula/image-sync-formula.changes
image-sync-formula/image-synchronize/sync.sls
image-sync-formula/metadata/form.yml

Fixes https://github.com/SUSE/spacewalk/issues/18638
The second commit deletes cached files that are no longer needed.

Add support to filter individual image versions in whitelist, improved cache handling

---

image-sync-formula/_modules/image_sync.py
image-sync-formula/image-sync-formula.changes

Fixes https://github.com/SUSE/spacewalk/issues/22209

Fix boot image version sort to use numeric compare

---

saltboot-formula/saltboot-formula.spec

- we don't want to package salt directories, rather require salt to be installed

Fix saltboot packaging

---

dracut-saltboot/dracut-saltboot.changes
dracut-saltboot/saltboot/saltboot.sh

For some reason sometimes dracut-wicked can generate multiple leaseinfo files. This PR tries to pickup the fist one with PXE info in it, if that is not found it blindly takes first available.
In the non-containerized deployment we do not add IPAPPEND for the PXE so we cannot count with BOOTIF present on the kernel command line to check the interface we booted from, let's use this heuristic.

Load first available leaseinfo, prefer those with BOOTFILE set

---

POS_Image-RPi-Bootstrap/POS_Image-RPi-Bootstrap.changes
POS_Image-RPi-Bootstrap/POS_Image-RPi-Bootstrap.kiwi

Package kbd is no longer installed via dependencies.
POS_Image-RPi-Bootstrap does not need any keyboard map.

Do not specify keytable in POS_Image-RPi-Bootstrap

---

python-susemanager-retail/python-susemanager-retail.changes
python-susemanager-retail/retail_create_delta

This script is by default only available on the server container, however inside container because of hairpin problem we cannot use image URLs as set in the pillar. This PR modifies download URL to use API host instead (and disable SSL verification because of it).
Also removes socket.getFqdn for delta url and use host from image url instead.
Issue: https://github.com/SUSE/spacewalk/issues/24648

Replace image download URLs based on API host

---

saltboot-formula/_states/saltboot.py
saltboot-formula/saltboot-formula.changes

Dracut saltboot stop file checks only for presence as it has pid information when starting minion.
So first rely on grains pid info and then check if we happen to have pid files and issue kill.
If none is available, rely on external kill from dracut.

Rework request stop function to avoid unnecessary warnings
