uyuni-project/retail

image-sync-formula/_modules/image_sync_usb.py, image-sync-formula/image-sync-formula.changes
This salt module creates usb image that can be used for booting terminals.
=> Add image_sync_usb module

image-sync-formula/_states/image_sync.py, image-sync-formula/image-sync-formula.changes
https://github.com/SUSE/spacewalk/issues/10075
=> Keep image bundles in /var/cache/salt/minion/extrn_files/

dracut-saltboot/dracut-saltboot.changes, dracut-saltboot/saltboot/module-setup.sh, saltboot-formula/_states/saltboot.py, saltboot-formula/saltboot-formula.changes
* Force fsck before image resize
*  Include swapon in saltboot initrd
=> SLE15 deploy fixes

branch-network-formula/branch-network/init.sls
Fix missing space in https://github.com/uyuni-project/retail/pull/22
=> Fix previous commit: add missing space

kiwi-desc-saltboot/kiwi-desc-saltboot.changes, kiwi-desc-saltboot/kiwi-desc-saltboot.spec
fixes https://github.com/SUSE/spacewalk/issues/10770
=> Limit archs to i585 and x86_64 depending SLE version

image-sync-formula/image-sync-formula.changes, image-sync-formula/image-synchronize/sync.sls
needed for https://github.com/SUSE/spacewalk/issues/9233
=> Install dosfstools for sync_image_usb module

image-sync-formula/image-sync-formula.changes, image-sync-formula/image-synchronize/sync.sls, saltboot-formula/_states/saltboot.py, saltboot-formula/saltboot-formula.changes
Send image_synced event in image-sync formula, 
use synced flag in saltboot formula.
This depends on https://github.com/uyuni-project/uyuni/pull/2761
=> Handle image synced flag

python-susemanager-retail/python-susemanager-retail.changes, python-susemanager-retail/susemanager/retail/branch.py
fixes https://github.com/SUSE/spacewalk/issues/12979
=> Skip internal initialization of excluded formulas

saltboot-formula/_states/saltboot.py, saltboot-formula/saltboot-formula.changes
Make sure the error message contains all the info needed for debugging.
=> Better error reporting on boot image download (bsc#1185509)

branch-network-formula/branch-network-formula.changes, branch-network-formula/branch-network/files/defaults.template, dracut-saltboot/dracut-saltboot.changes, dracut-saltboot/saltboot/saltboot.sh, saltboot-formula/_states/saltboot.py, saltboot-formula/saltboot-formula.changes
https://github.com/SUSE/spacewalk/issues/14943
=> Use kernel parameters from PXE formula also for local boot

python-susemanager-retail/retail_create_delta
For now it still must be run on the server.
This will be changed as soon as there is API for uploading image files.
=> Create deltas using API

POS_Image-Graphical7/POS_Image-Graphical7.changes, POS_Image-JeOS7/POS_Image-JeOS7.changes, saltboot-formula/_states/saltboot.py, saltboot-formula/saltboot-formula.changes, saltboot-formula/saltboot-reactor/pxe_update.sls
- also update changes on released packages
=> Use always the same URL when downloading image

dracut-saltboot/dracut-saltboot.changes, dracut-saltboot/saltboot/saltboot.sh
- Fix network loading when ipappend is used by limiting search to  ipv4 leases info
- Add couple new information messages
=> Wait for network setup up to 30s

python-susemanager-retail/python-susemanager-retail.changes, python-susemanager-retail/retail_create_delta, python-susemanager-retail/susemanager/retail/log.py
consistently use susemanager.retail.log
=> Fix messages and logging in retail_create_delta (bsc#1199727)

image-sync-formula/_modules/image_sync.py, image-sync-formula/_states/image_sync.py, image-sync-formula/image-sync-formula.changes, python-susemanager-retail/python-susemanager-retail.changes, python-susemanager-retail/retail_create_delta
This adds support for deltas on system (kis) images.
=> Support deltas for system images (bsc#1201498)

saltboot-formula/_states/saltboot.py, saltboot-formula/saltboot-formula.changes
=> Backport of saltboot fallback mechanism

image-sync-formula/_modules/image_sync.py, image-sync-formula/image-sync-formula.changes, image-sync-formula/image-synchronize/sync.sls
Fixes https://github.com/SUSE/spacewalk/issues/17207
=> Add function to select latest version of boot image

dracut-saltboot/dracut-saltboot.changes, dracut-saltboot/saltboot/saltboot.sh
Load network configuration even when missing protocol version and include some shellcheck fixes for that part of the code.
=> Load network configuration even when missing protocol version

image-sync-formula/_modules/image_sync.py, image-sync-formula/image-sync-formula.changes
Fixes https://github.com/SUSE/spacewalk/issues/19489
Depends on https://github.com/SUSE/salt-formulas/pull/193
=> Do not delete boot images which are referenced in PXE entries

saltboot-formula/_states/saltboot.py, saltboot-formula/saltboot-formula.changes
Fixes https://github.com/SUSE/spacewalk/issues/21884
=> Understand pillar based repartitioning

image-sync-formula/image-sync-formula.changes, image-sync-formula/image-sync-formula.rpmlintrc, image-sync-formula/image-sync-formula.spec
- Add missing URL
- Update license to  SPDX syntax
- Silence rpmlint warnings `description-shorter-than-summary` `filename-too-long-for-joliet`
=> Add missing URL and update the spec file

python-susemanager-retail/python-susemanager-retail.changes, python-susemanager-retail/susemanager/retail/branch.py
This PR adds detection of containerized branch server and if detected, it skips the branch formulas and configure
saltboot group instead.
Fixes https://github.com/SUSE/spacewalk/issues/24041
=> Handle containerized branch server in retail_yaml (bsc#1222128)

saltboot-formula/_states/saltboot.py, saltboot-formula/saltboot-formula.changes
See $topic
Fixes https://github.com/SUSE/spacewalk/issues/26610
=> Support local boot to deployed kernel even when version does not match pillar boot version

dracut-saltboot/dracut-saltboot.changes, dracut-saltboot/saltboot/module-setup.sh
=> Add missing chroot dependency for bootloader installation
